[package]
name = "zerozero"
version = "0.1.0"
edition = "2021"
authors = ["Jan Machacek <janmachacek97@gmail.com>"]

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
reqwest = "0.11.14"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
